### PR TITLE
Setting

### PR DESCRIPTION
**Pull request by linjiang82**
**Problem:**
The change username and password unimplemented.

**Solution:**
Implemented the functions to change username and password.

**Todo:**
Would like an error message to be displayed when the old pin incorrect or the new pin and the confirm pin not match. UI won't update even though the state has been set. Welcome a discussion about it.

### CODE REVIEW

**Review by KipCrossing — CHANGES_REQUESTED** [review]
This is great!

Some small requests:
- [ ] Pin data is removed on closing the draw 
- [ ] User feedback when the pin is incorrect 
- [ ] Could you update the link for *Submit an issue/feedback* to use https://docs.google.com/forms/d/e/1FAIpQLScFzoEslP6z4oStSYaOROCWSELb2Y9vESB2VT7fsLRZplRP_A/viewform?usp=sf_link

The last one was a bit of an F up on our end.

**Comment by linjiang82** [comment]
> This is great!
> 
> Some small requests:
> 
> * [ ]  Pin data is removed on closing the draw
> * [ ]  User feedback when the pin is incorrect
> * [ ]  Could you update the link for _Submit an issue/feedback_ to use https://docs.google.com/forms/d/e/1FAIpQLScFzoEslP6z4oStSYaOROCWSELb2Y9vESB2VT7fsLRZplRP_A/viewform?usp=sf_link
> 
> The last one was a bit of an F up on our end.

The second item was what I wanted to-do in the first place,  but  the prompt msg could not pop up without reopening the drawer,  still need to find a solution for it or if anyone knows,  I would like a discussion

**Comment by KipCrossing** [comment]
> The second item was what I wanted to-do in the first place, but the prompt msg could not pop up without reopening the drawer, still need to find a solution for it or if anyone knows, I would like a discussion

When you set state, you are setting the state for the whole page - and hence *'closing the draw'*.

What you want to do is to abstract the contents of the draw into its own stateful widget. I'm about to push a commit when I abstracted the "Change username" draw container into a stateful widget called **UsernameUpdater**.

Review this commit and let me know if it makes sense.

**Comment by KipCrossing** [comment]
You'll need to do the dame with the "change pin" draw.

**Review by oscarmanderj — APPROVED** [review]
This looks great - very smooth, well done.

**Review by KipCrossing — APPROVED** [review]
AWESOME!

**Pull request merged**
